---
collections:
  - name: ansible.eda
    source: https://galaxy.ansible.com
  - name: cloud.datadog
    version: '>=1.0.0'
  - name: cloud.prometheus
    version: '>=1.0.0'
  - name: ansible.utils
    version: '>=2.0.0'
  - name: dynatrace.event_driven_ansible
    source: https://galaxy.ansible.com
  - name: crowdstrike.falcon
    source: https://galaxy.ansible.com
  - name: kubealex.eda
    source: https://galaxy.ansible.com
  - name: community.general
    version: ">=7.0.0"
