---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--ignore-errors'
  ANSIBLE_GALAXY_CLI_ROLE_OPTS: '--ignore-errors'
  PKGMGR_PRESERVE_CACHE: 'false'

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-25/ee-supported-rhel9:latest'
    options:
      pull_policy: missing
      tls_verify: false

options:
  package_manager_path: /usr/bin/microdnf

additional_build_files:
  - src: /tmp/ee-containers/_build/configs/ansible.cfg
    dest: configs/ansible.cfg

dependencies:
  ansible_core:
    package_pip: ansible-core>=2.13.10
  ansible_runner:
    package_pip: ansible-runner>=2.4.0
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  prepend_base: |
    USER root
    RUN microdnf upgrade -y && \
        microdnf install -y gcc make pkg-config python3-devel systemd-devel && \
        python3 -m pip install --upgrade pip setuptools wheel && \
        rpm -e ansible-core --nodeps && \
        python3 -m pip install --upgrade ansible-core ansible-runner

  prepend_final: |
    USER root
    RUN microdnf upgrade -y && \
        microdnf install -y python39-pip python39-devel gcc && \
        python3 -m pip install --no-cache-dir --upgrade ansible-core ansible-runner

  append_final: |
    USER root
    RUN microdnf clean all && \
        rm -rf /var/cache/{dnf,yum}
