---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--ignore-errors'
  ANSIBLE_GALAXY_CLI_ROLE_OPTS: '--ignore-errors'
  PKGMGR_PRESERVE_CACHE: 'false'

options:
  package_manager_path: /usr/bin/microdnf

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-25/ee-supported-rhel8:latest'
    options:
      pull_policy: missing
      tls_verify: false

additional_build_files:
  - src: ./ansible.cfg
    dest: configs/ansible.cfg

dependencies:
  ansible_core:
    package_pip: "ansible-core>=2.15.0,<2.16"
  ansible_runner:
    package_pip: "ansible-runner>=2.3.1"
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  prepend_base: |
    USER root
    RUN python3 -m pip uninstall ansible ansible-core ansible-lint ansible-runner || true && \
        rpm --rebuilddb && \
        rpm -qa >/dev/null 2>&1 && \
        microdnf remove -y \
            ansible-core \
            ansible-lint \
            python3.11-ansible-compat \
            python3-ansible-core || true && \
        microdnf install -y \
            python3 \
            shadow-utils \
            sudo \
            python3-pip \
            python3-devel \
            gcc \
            make \
            pkg-config \
            systemd-devel \
            systemd \
            python3-systemd \
            systemd-libs && \
        useradd -m -s /bin/bash admin && \
        echo "admin:redhat" | chpasswd && \
        echo "admin ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && \
        chown -R admin:admin /home/admin && \
        python3 -m pip install --upgrade pip setuptools wheel

  prepend_final: |
    USER root
    RUN pip3 uninstall -y ansible-core ansible-lint ansible-runner && \
        python3 -m pip install --no-cache-dir --break-system-packages \
            "ansible-core>=2.15.0,<2.16" \
            "ansible-runner>=2.3.1" \
            "ansible-compat>=4.1.11" \
            "ansible-lint>=24.9.0" && \
        ln -sf /usr/lib64/libsystemd.so.0 /usr/lib64/libsystemd.so && \
        ln -sf /usr/lib64/libsystemd.so.0 /usr/lib64/libsystemd-journal.so && \
        ln -sf /usr/lib64/pkgconfig/libsystemd.pc /usr/lib64/pkgconfig/systemd.pc

  append_final: |
    USER root
    RUN mkdir -p /etc/ansible && \
        echo "[defaults]" > /etc/ansible/ansible.cfg && \
        echo "remote_tmp = /tmp/.ansible-\${USER}/tmp" >> /etc/ansible/ansible.cfg && \
        microdnf clean all && \
        rm -rf /var/cache/{dnf,yum}


