---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre --ignore-errors'
  ANSIBLE_GALAXY_CLI_ROLE_OPTS: '--ignore-errors'

options:
  package_manager_path: /usr/bin/microdnf

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-25/ee-supported-rhel8:latest'
    options:
      pull_policy: missing
      tls_verify: false

additional_build_files:
  - src: ./ansible.cfg
    dest: configs/ansible.cfg

dependencies:
  ansible_core:
    package_pip: ansible-core>=2.13.10
  ansible_runner:
    package_pip: ansible-runner>=2.0.0
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  prepend_final: |
    RUN microdnf update -y \
        && microdnf install -y python3-pip python3-devel gcc python3-wheel python3-setuptools \
           systemd-devel pkgconf-pkg-config libsystemd-devel systemd-libs make systemd \
        && python3 -m pip install --no-cache-dir --upgrade pip setuptools wheel \
        && python3 -m pip install --no-cache-dir --ignore-installed typing-extensions aiohttp \
        && python3 -m pip install --no-cache-dir ansible-core>=2.13.10 ansible-runner

  append_final: |
    RUN microdnf clean all \
      && rm -rf /var/cache/{dnf,yum} \
      && rm -rf /var/lib/dnf/history.* \
      && rm -rf /var/log/dnf.* /var/log/hawkey.log \
      && rm -rf /var/cache/dnf \
      && rm -rf /root/.cache \
      && rm -rf /etc/ansible/ansible.cfg
