---
galaxy_info:
  author: Your Name
  description: Role for building Ansible Execution Environments.
  company: Your Company
  license: license (e.g., MIT)
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Ubuntu
      versions:
        - bionic
        - focal

dependencies: []
