---
galaxy_info:
  author: Shadd
  description: Role for building Ansible Execution Environments with container images.
  company: Red Hat, Inc.
  license: GPL-3.0-or-later
  min_ansible_version: 2.9

  platforms:
    - name: EL
      versions:
        - 8
        - 9
    - name: RHEL
      versions:
        - 8
        - 9
    - name: Fedora
      versions:
        - all

  galaxy_tags:
    - ansible
    - automation
    - containers
    - execution_environment
    - podman
    - buildah
    - ee
    - development

dependencies: []
