---
- name: Build container image
  ansible.builtin.command:
    cmd: >-
      ansible-builder build
      --prune-images
      --no-cache
      -v3
      -f {{ selected_env }}/execution-environment.yml
      --context {{ work_dir }}
      --tag {{ selected_env | basename }}
  async: 2800
  poll: 0
  register: build_job

- name: Wait for build completion
  ansible.builtin.async_status:
    jid: "{{ build_job.ansible_job_id }}"
  register: build_result
  until: build_result.finished
  retries: 30
  delay: 60