---
# Environment Selection Menu

- name: Ensure environments directory exists
  ansible.builtin.file:
    path: "environments"
    state: directory
    mode: '0755'

- name: Display environment filter information
  ansible.builtin.debug:
    msg: |
      Distribution filter active: {{ (build_rhel8 | bool) | ternary('RHEL 8', '') }}{{ (build_rhel8 and build_rhel9) | ternary(' and ', '') }}{{ (build_rhel9 | bool) | ternary('RHEL 9', '') }}

- name: Check if environment_paths is defined and not empty
  ansible.builtin.debug:
    msg: "Environment paths received: {{ environment_paths | default([]) | length }} paths"
    verbosity: 1

- name: Find environment directories directly
  ansible.builtin.find:
    paths: "environments"
    file_type: directory
  register: found_environments

- name: Debug found environments
  ansible.builtin.debug:
    msg: "Found environments: {{ found_environments.files | map(attribute='path') | map('basename') | list }}"
    verbosity: 1

- name: Filter environments based on distribution selection
  ansible.builtin.set_fact:
    environment_names: "{% if build_rhel8 and build_rhel9 %}{{ found_environments.files | map(attribute='path') | map('basename') | list }}{% elif build_rhel8 %}{{ found_environments.files | map(attribute='path') | map('basename') | select('search', 'rhel8') | list }}{% elif build_rhel9 %}{{ found_environments.files | map(attribute='path') | map('basename') | select('search', 'rhel9') | list }}{% else %}{{ found_environments.files | map(attribute='path') | map('basename') | list }}{% endif %}"

- name: Show filtered environment names
  ansible.builtin.debug:
    msg: |
      Filtered environments for {{ (build_rhel8 | bool) | ternary('RHEL 8', '') }}{{ (build_rhel8 and build_rhel9) | ternary(' and ', '') }}{{ (build_rhel9 | bool) | ternary('RHEL 9', '') }}:
      {% for env in environment_names %}
      - {{ env }}
      {% endfor %}

- name: Check if any environments are available
  ansible.builtin.fail:
    msg: |
      No environment directories matching your distribution selection were found.
      
      Distribution filter: {{ (build_rhel8 | bool) | ternary('RHEL 8', '') }}{{ (build_rhel8 and build_rhel9) | ternary(' and ', '') }}{{ (build_rhel9 | bool) | ternary('RHEL 9', '') }}
      
      Available directories that didn't match your filter:
      {% for env in found_environments.files | map(attribute='path') | map('basename') | list %}
      - {{ env }}
      {% endfor %}
      
      To see all environments, select 'both' for the distribution selection.
  when: environment_names | length == 0

- name: Display environment selection menu header
  ansible.builtin.debug:
    msg: |
      **************************************************
      ENVIRONMENT SELECTION MENU
      
      Selected distribution: {{ (build_rhel8 | bool) | ternary('RHEL 8', '') }}{{ (build_rhel8 and build_rhel9) | ternary(' and ', '') }}{{ (build_rhel9 | bool) | ternary('RHEL 9', '') }}
      Showing {{ environment_names | length }} compatible environments
      **************************************************

- name: Prompt for environment selection
  ansible.builtin.pause:
    prompt: |
      **************************************************
      ENVIRONMENT SELECTION MENU
      
      Selected distribution: {{ (build_rhel8 | bool) | ternary('RHEL 8', '') }}{{ (build_rhel8 and build_rhel9) | ternary(' and ', '') }}{{ (build_rhel9 | bool) | ternary('RHEL 9', '') }}
      
      Available environments:
      {% for env_name in environment_names %}
      {{ loop.index }}. {{ env_name }}
      {% endfor %}
      **************************************************

      Enter numbers for environments to build (comma-separated, max {{ environment_names | length }})
      Enter 'all' to select all environments
      Enter 'q' to quit without selecting
  register: env_selection
  
- name: Process environment selection
  ansible.builtin.set_fact:
    selected_indices: "{{ env_selection.user_input.split(',') | map('trim') | select('match', '^[0-9]+$') | map('int') | select('<=', environment_names | length) | select('>=', 1) | list }}"
    select_all: "{{ env_selection.user_input | trim | lower == 'all' }}"
    quit_selection: "{{ env_selection.user_input | trim | lower == 'q' }}"

- name: Select all environments when requested
  ansible.builtin.set_fact:
    selected_environments: "{{ environment_names }}"
  when: select_all | bool

- name: Convert indices to environment names
  ansible.builtin.set_fact:
    selected_environments: "{{ selected_indices | map('extract', environment_names, 1) | list }}"
  when: selected_indices | length > 0 and not select_all | bool and not quit_selection | bool

- name: Set empty selection when nothing valid was entered or quit selected
  ansible.builtin.set_fact:
    selected_environments: []
  when: (selected_indices | default([]) | length == 0 and not select_all | bool) or quit_selection | bool

- name: Show selected environments
  ansible.builtin.debug:
    msg: |
      Selected environments for building: 
      {% if selected_environments | length > 0 %}
      {% for env in selected_environments %}
      - {{ env }}
      {% endfor %}
      {% else %}
      No environments selected for building.
      {% endif %}
