- name: Clean dangling images before building
  ansible.builtin.shell: podman image prune -f
  register: pre_prune
  changed_when: pre_prune.stdout is search("deleted")

- name: Update /tmp/current_env for monitoring showing build start
  ansible.builtin.copy:
    content: "STARTING: {{ item | basename }}"
    dest: /tmp/current_env
  changed_when: false

- name: Set work_dir for the current environment
  ansible.builtin.set_fact:
    work_dir: "/tmp/ee-builder/context/environments/{{ item | basename }}"

# Wrap the build process in a block with rescue
- name: "Build environment {{ item | basename }}"
  block:
    - name: Debug work_dir
      ansible.builtin.debug:
        msg: "Work directory: {{ work_dir }}"
    
    - name: Build container image using ansible-builder
      ansible.builtin.shell: |
        cd {{ work_dir }} && \
        ansible-builder build \
          --tag {{ item | basename }} \
          --
