- name: Set work_dir for the current environment
  ansible.builtin.set_fact:
    work_dir: "/tmp/ee-builder/context/environments/{{ item | basename }}"
    build_context: "/tmp/ee-builder/context/environments/{{ item | basename }}"

- name: Debug work_dir
  ansible.builtin.debug:
    msg: "Work directory: {{ work_dir }}"
  
- name: Create work_dir for the current environment
  ansible.builtin.file:
    path: "{{ work_dir }}"
    state: directory
    mode: '0755'

# Show that we're starting to build this environment in the monitoring display
- name: Update build status file - starting build
  ansible.builtin.shell: "BASENAME=$(basename {{ item }}) && echo $BASENAME > /tmp/current_env"
  changed_when: false

- name: Copy selected environment to work_dir
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ work_dir }}"
    remote_src: true

- name: Validate execution-environment.yml syntax
  ansible.builtin.command:
    cmd: "python3 -c \"import yaml; yaml.safe_load(open('{{ work_dir }}/execution-environment.yml'));\""
  register: yaml_validation
  changed_when: false
  failed_when: false

# Handle YAML validation failures
- name: Handle YAML validation failures
  when: yaml_validation.rc != 0
  block:
    - name: Update build status file - skipping build due to YAML error
      ansible.builtin.shell: "BASENAME=$(basename {{ item }}) && echo SKIPPED: $BASENAME \\(invalid YAML\\) > /tmp/current_env"
      changed_when: false
      
    - name: Debug skip message
      ansible.builtin.debug:
        msg: "SKIPPING BUILD due to invalid YAML in execution-environment.yml"
        
    - name: Record skipped build in results
      ansible.builtin.set_fact:
        build_results: "{{ build_results | default([]) + [{'image': item | basename, 'success': false, 'output': {'rc': 1, 'stderr': 'Invalid YAML syntax in execution-environment.yml', 'stderr_lines': ['Invalid YAML syntax in execution-environment.yml']}}] }}"
        cacheable: true
      changed_when: false
      
    - name: Skip remaining tasks for this environment
      ansible.builtin.meta: end_play
        
# Only run build if YAML validation passed
- name: Build container image using ansible-builder
  ansible.builtin.command:
    cmd: >
      ansible-builder build
      --tag {{ item | basename }}
      --container-runtime podman
      --verbosity 3
      --prune-images
      --context {{ build_context }}
      -f {{ build_context }}/execution-environment.yml
      --build-arg AH_TOKEN="{{ automation_hub_token }}"
  args:
    chdir: "{{ build_context }}"
  environment:
    ANSIBLE_BUILDER_HOME: "{{ build_context }}"
    PODMAN_IGNORE_CGROUPSV1_WARNING: 1
  register: build_output
  changed_when: build_output.rc == 0
  # Don't make this task fail, we'll handle failures later
  failed_when: false
