---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_ROLE_OPTS: "--ignore-errors"
  PKGMGR_PRESERVE_CACHE: "false"

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-25/de-supported-rhel9:latest'

additional_build_files:
  - src: templates/ansible.cfg.j2
    dest: configs/ansible.cfg

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

options:
  package_manager_path: /usr/bin/microdnf

additional_build_steps:
  prepend_final: |
    RUN microdnf upgrade -y
    RUN microdnf install -y \
        gcc \
        make \
        pkg-config \
        python3-devel \
        python3-pip \
        python3-setuptools \
        systemd-devel \
        python3-wheel \
        ansible-core \
        ansible-runner 

    # Set PKG_CONFIG_PATH and ensure systemd files are found
    ENV PKG_CONFIG_PATH=/usr/lib64/pkgconfig:/usr/share/pkgconfig
    RUN ln -s /usr/lib64/pkgconfig/libsystemd.pc /usr/lib64/pkgconfig/systemd.pc

    RUN pip3 install --upgrade pip setuptools wheel

  append_final: |
    RUN microdnf clean all && \
        rm -rf /var/cache/{dnf,yum} && \
        rm -rf /etc/ansible/ansible.cfg
