---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: ""

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-25/ee-supported-rhel9:latest'

additional_build_files:
  - src: ./ansible.cfg
    dest: configs

dependencies:
  ansible_core:
    package_pip: ansible-core>=2.13.10
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

options:
  package_manager_path: /usr/bin/microdnf

additional_build_steps:
  prepend_final: |
    RUN microdnf upgrade -y \
        && microdnf install -y python39-pip python39-devel gcc \
        && python3 -m pip install --no-cache-dir --upgrade pip setuptools wheel \

  append_final: |
    ARG ANSIBLE_GALAXY_CLI_ROLE_OPTS=" --ignore-errors"
    RUN microdnf clean all \
      && rm -rf /var/cache/{dnf,yum} \
      && rm -rf /var/lib/dnf/history.* \
      && rm -rf /var/log/dnf.* /var/log/hawkey.log \
      && rm -rf /var/cache/dnf \
      && rm -rf /root/.cache \
      && rm -rf /etc/ansible/ansible.cfg
