---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel8:latest

dependencies:
  galaxy:
    collections:
      - community.general
      - cloud.terraform
  python: requirements.txt
  system: bindep.txt

options:
  package_manager_path: /usr/bin/microdnf

additional_build_steps:
  prepend_base: |
    USER root
    # Using custom assemble script
    COPY scripts/assemble /output/scripts/assemble
    RUN chmod +x /output/scripts/assemble

  prepend_galaxy: |
    # Skip systemd-python during galaxy build due to compilation issues
    RUN echo "Skipping systemd-python due to compilation issues"

  prepend_final: |
    USER root
    # Install Go compiler if needed for terraform-inventory
    RUN microdnf install -y golang gcc
    
    # Download pre-compiled terraform-inventory binary instead of building from source
    RUN mkdir -p /tmp/terraform-tools && cd /tmp/terraform-tools && \
        curl -L https://github.com/adammck/terraform-inventory/releases/download/v0.10/terraform-inventory_v0.10_linux_amd64.zip -o terraform-inventory.zip && \
        unzip terraform-inventory.zip && \
        chmod +x terraform-inventory && \
        mv terraform-inventory /usr/local/bin/ && \
        cd /tmp && \
        rm -rf /tmp/terraform-tools

  append_final: |
    USER root
    # Clean up
    RUN microdnf clean all && \
        rm -rf /var/cache/{dnf,yum} && \
        rm -rf /var/lib/dnf/history.* && \
        rm -rf /var/log/dnf.* /var/log/hawkey.log
        
    # Verify terraform and terraform-inventory installation
    RUN command -v terraform && terraform version || echo "Terraform not installed" && \
        command -v terraform-inventory && terraform-inventory --help || echo "Terraform-inventory not installed"
    
    # Verify our custom systemd module works
    RUN python3 -c "try: import systemd; from systemd import journal; print('Custom systemd module loaded successfully'); except ImportError as e: print(f'Warning: {e}');"
