---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--ignore-errors'
  ANSIBLE_GALAXY_CLI_ROLE_OPTS: '--ignore-errors'
  PKGMGR_PRESERVE_CACHE: 'false'

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-25/ee-supported-rhel9:latest'
    options:
      pull_policy: missing
      tls_verify: false

options:
  package_manager_path: /usr/bin/microdnf

additional_build_files:
  - src: /tmp/ee-containers/_build/configs/ansible.cfg
    dest: configs/ansible.cfg

dependencies:
  ansible_core:
    package_pip: ansible-runner>=2.4.0
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  prepend_base: |
    USER root
    RUN microdnf upgrade -y && \
        microdnf install -y gcc make pkg-config python3-devel python3-pip systemd-devel \
        libxml2-devel dnf yum-utils openssl-devel rpm-build krb5-devel krb5-libs krb5-workstation && \
        rpm -e ansible-core --nodeps || true && \

  prepend_final: |
    USER root
    RUN python3 -m pip install --no-cache-dir --upgrade --ignore-installed pip setuptools wheel && \
        python3 -m pip install --no-cache-dir --upgrade --ignore-installed ansible-core ansible-runner

  append_final: |
    USER root
    # Check for any package issues but don't fail the build
    RUN pip3 check || echo "Some packages have issues, but continuing the build"
    RUN microdnf clean all && \
        rm -rf /var/cache/{dnf,yum} && \
        echo "Build completed successfully"

  prepend_builder: |
    RUN pip3 install --upgrade --ignore-installed pip setuptools wheel  \
        && touch /requirements.txt

  append_builder: |
    USER root
    RUN microdnf clean all && \
        rm -rf /var/cache/{dnf,yum} && \
        rm -rf /etc/ansible/ansible.cfg \\
        echo "Build completed successfully" && echo "Requirements test file created successfully"
    RUN pip3 check || echo "Some packages have issues, but continuing the build"
