---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel9:latest
    options:
      pull_policy: missing
      tls_verify: false

dependencies:
  galaxy:
    collections:
      - { name: ansible.utils, version: 5.1.2 }
      - { name: community.vmware, version: 5.0.1 }
      - { name: vmware.vmware_rest, version: 4.1.0 }
  python:
    - aiohttp>=3.8.5
    - pyVmomi>=6.7
    - git+https://github.com/vmware/vsphere-automation-sdk-python.git 

options:
  package_manager_path: /usr/bin/microdnf

additional_build_steps:
  prepend_base: |
    USER root
    RUN microdnf upgrade -y && \
        microdnf install -y gcc make pkg-config python3-devel python3-pip systemd-devel \
        libxml2-devel dnf yum-utils openssl-devel rpm-build krb5-devel krb5-libs krb5-workstation && \
        rpm -e ansible-core --nodeps || true && \

  prepend_final: |
    USER root
    RUN python3 -m pip install --no-cache-dir --upgrade --ignore-installed pip setuptools wheel && \
        python3 -m pip install --no-cache-dir --upgrade --ignore-installed ansible-core ansible-runner && \
        python3 -m pip install --no-cache-dir --upgrade --ignore-installed requests && \
        python3 -m pip install --no-cache-dir --upgrade --ignore-installed numpy && \
        python3 -m pip install --no-cache-dir --upgrade --ignore-installed pandas && \
        python3 -m pip install --no-cache-dir --upgrade --ignore-installed pyVmomi

  append_final: |
    USER root
    RUN microdnf clean all && \
        rm -rf /var/cache/{dnf,yum} && \
        rm -rf /etc/ansible/ansible.cfg \\
        echo "Build completed successfully" && echo "Requirements test file created successfully"
    RUN pip3 check || echo "Some packages have issues, but continuing the build"