---
collections:
  - name: community.general
  - name: community.vmware
  - name: community.postgresql
  - name: vmware.vmware_rest
  - name: vmware.vmware
  - name: ansible.hub
  - name: infra.aap_utilities
  - name: infra.controller_configuration
  - name: infra.aap_configuration
  - name: containers.podman
  - name: oneidentity.safeguardcollection
  - name: community.hashi_vault
  - name: kubernetes.core
    #  - name: cloud.vmware_ops
