---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--ignore-errors'
  ANSIBLE_GALAXY_CLI_ROLE_OPTS: '--ignore-errors'
  PKGMGR_PRESERVE_CACHE: 'false'

options:
  package_manager_path: /usr/bin/microdnf

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-25/ee-supported-rhel8:latest'
    options:
      pull_policy: missing
      tls_verify: false

additional_build_files:
  - src: ./ansible.cfg
    dest: configs/ansible.cfg

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  prepend_base: |
    USER root
    python3 -m pip install --upgrade pip setuptools wheel
    RUN microdnf upgrade -y && \
        useradd -m -s /bin/bash admin && \
        echo "admin:redhat" | chpasswd && \
        echo "admin ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && \
        chown -R admin:admin /home/admin && \

  prepend_final: |
    USER root
    RUN ln -sf /usr/lib64/libsystemd.so.0 /usr/lib64/libsystemd.so && \
        ln -sf /usr/lib64/libsystemd.so.0 /usr/lib64/libsystemd-journal.so && \
        ln -sf /usr/lib64/pkgconfig/libsystemd.pc /usr/lib64/pkgconfig/systemd.pc

  append_final: |
    USER root
    RUN mkdir -p /etc/ansible && \
        echo "[defaults]" > /etc/ansible/ansible.cfg && \
        echo "remote_tmp = /tmp/.ansible-\${USER}/tmp" >> /etc/ansible/ansible.cfg && \
        microdnf clean all && \
        rm -rf /var/cache/{dnf,yum}
        