---
version: 3

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel9:latest'
    options:
      pull_policy: missing
      tls_verify: false

dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  galaxy:
    collections:
      - { name: amazon.aws, version: 9.2.0 }
      - { name: azure.azcollection, version: 3.2.0 }
      - { name: community.aws, version: 6.3.0 }
      - { name: community.digitalocean, version: 1.27.0 }
      - { name: google.cloud, version: 1.5.1 }
      - { name: hetzner.hcloud, version: 4.0.1 }
      - { name: vultr.cloud, version: 1.10.0 }
  python:
    - awscli>=1.16.312
    - botocore>=1.34.0
    - boto3>=1.34.0

options:
  package_manager_path: /usr/bin/microdnf

additional_build_steps:
  prepend_base: |
    USER root
    RUN microdnf install -y shadow-utils sudo python3-pip systemd-devel && \
        useradd -m -s /bin/bash admin && \
        echo "admin:redhat" | chpasswd && \
        echo "admin ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && \
        chown -R admin:admin /home/admin && \
        python3 -m pip install --user --ignore-installed --no-cache-dir --upgrade pip setuptools wheel && \
        python3 -m pip install --user --ignore-installed --no-cache-dir --upgrade ansible-core>=2.13.10 ansible-runner

  prepend_final: |
    USER root
    RUN microdnf install -y gcc make pkg-config python3-devel systemd-devel && \
        ln -sf /usr/lib64/libsystemd.so.0 /usr/lib64/libsystemd-journal.so && \
        ansible --version && \
        ansible-runner --version

  append_final: |
    USER root
    RUN mkdir -p /etc/ansible && \
        echo "[defaults]" > /etc/ansible/ansible.cfg && \
        echo "remote_tmp = /tmp/.ansible-\${USER}/tmp" >> /etc/ansible/ansible.cfg && \
        microdnf clean all && \
        rm -rf /var/cache/{dnf,yum}


  
