---
version: 3

build_arg_defaults: {}

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel9:latest'
    options:
      pull_policy: missing
      tls_verify: false

additional_build_files:
  - src: ./ansible.cfg
    dest: configs

dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

options:
  package_manager_path: /usr/bin/microdnf

additional_build_steps:
  prepend_final: |
    RUN microdnf install -y python3 python3-pip && \
      python3 -m pip install --user --ignore-installed --no-cache-dir --upgrade pip setuptools wheel && \
      python3 -m pip install --user --ignore-installed --no-cache-dir --upgrade ansible-core ansible-runner && \
      microdnf upgrade -y && \
      pip3 cache purge       

  append_final: |
    ARG ANSIBLE_GALAXY_CLI_ROLE_OPTS=" --ignore-errors"
    RUN microdnf clean all \
      && rm -rf /var/cache/{dnf,yum} \
      && rm -rf /var/lib/dnf/history.* \
      && rm -rf /var/log/dnf.* /var/log/hawkey.log \
      && rm -rf /var/cache/dnf \
      && rm -rf /root/.cache \
      && rm -rf /etc/ansible/ansible.cfg
