---
version: 3

build_arg_defaults: {}

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel9:1.0.0-808'

additional_build_files:
  - src: ./ansible.cfg
    dest: configs

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

options:
  package_manager_path: /usr/bin/microdnf

additional_build_steps:
  prepend_final: |
      RUN pip3 install --upgrade pip setuptools
      RUN microdnf upgrade -y
      RUN microdnf clean all
      RUN pip3 cache purge    

  append_final: |
    ARG ANSIBLE_GALAXY_CLI_ROLE_OPTS=" --ignore-errors"