---
version: 3
 
images:
  base_image:
    name: svm2898pdv.csdev.corp/ansible-automation-platform-24/ee-minimal-rhel9:latest
 
build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '-c'
 
dependencies:
  galaxy: collections/requirements.yml
  python: python/requirements.txt
  system: bindep.txt
 
options:
  package_manager_path: /usr/bin/microdnf
 
 
additional_build_files:
  # Can be used to resolve collections from private automation hub
  - src: ansible.cfg
    dest: configs
      # - src: rpms/openshift-clients-4.12.0-202307200611.p0.g49844f7.assembly.stream.el8.x86_64.rpm
      # dest: rpms
 
 
additional_build_steps:
  prepend_base:
    # - RUN microdnf install -y python3.12
    # - RUN mv /usr/bin/python3 /usr/bin/python3.old && ln -s /usr/bin/python3.12 /usr/bin/python3
    - RUN python3 -m ensurepip --upgrade
    - RUN git config --global http.sslVerify false
      #- COPY _build/rpms/*.rpm /tmp/openshift-clients.rpm
    - RUN $PKGMGR install bash-completion
      #- RUN rpm -ivh /tmp/openshift-clients.rpm
  prepend_galaxy:
    # Add custom ansible.cfg which defines collection install sources
    - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg
   append_final:
    - RUN microdnf install -y --enablerepo=rhocp-4.10-for-rhel-8-x86_64-rpms --releasever=8.6 openshift-clients
    - RUN ansible-galaxy collection install redhat.openshift

 
