---
images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel9:latest
    options:
      pull_policy: missing
      tls_verify: false

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  
ansible_config: '../ansible.cfg' 

additional_build_steps:
  prepend: |
    RUN pip3 install --upgrade pip setuptools
  # append: |
  #   LABEL quay.expires-after="45d"
 
