---
version: 3

# Replace the 'images' section with build_arg_defaults
build_arg_defaults:
  EE_BASE_IMAGE: registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel9:latest

dependencies:
  galaxy: requirements.yml
  python: requirements.txt

ansible_config: ../ansible.cfg

additional_build_steps:
  prepend: |
    RUN pip3 install --upgrade pip setuptools

