---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/ee-supported-rhel8:latest
    options:
      pull_policy: always
      tls_verify: false

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre --ignore-errors --force'
  ANSIBLE_GALAXY_CLI_ROLE_OPTS: '--ignore-errors --force'

additional_build_files:
  - src: ./ansible.cfg
    dest: configs

dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  galaxy:
    collections:
      - ansible.windows
      - community.windows
      - chocolatey.chocolatey
      - microsoft.sql
  system:
    - pkgconf-pkg-config [platform:rpm]
    - systemd-devel [platform:rpm]
    - gcc [platform:rpm]
    - python39-devel [platform:rpm]
  python:
    - pywinrm[kerberos]
    - krb5-libs
    - krb5-workstation
    - packaging
    - requests[security]
    - xmltodict
    - msgraph-sdk==1.0.0
    - psycopg2-binary
    - urllib3==1.26.15

additional_build_steps:
  prepend_final: |
    RUN /usr/bin/microdnf install -y yum-utils \
      && microdnf upgrade -y \
      && microdnf install -y python39-pip python39-devel gcc \
      && python3 -m pip install --user --ignore-installed --no-cache-dir --upgrade pip setuptools wheel \
      && python3 -m pip install --user --ignore-installed --no-cache-dir --upgrade ansible-core ansible-runner 

