---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/ee-supported-rhel8:latest


additional_build_files:
  - src: ./ansible.cfg
    dest: configs

dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml  # This will handle both roles and collections
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  prepend_base: |
    USER root
    # Fix DNF missing
    RUN if [ ! -f /usr/bin/dnf ] && [ -f /usr/bin/microdnf ]; then \
        microdnf install -y dnf; \
    fi
    
    # Existing commands...
    RUN microdnf upgrade -y && \
        microdnf install -y gcc make pkg-config python3-devel systemd-devel \
        libxml2-devel openssl-devel rpm-build krb5-devel krb5-libs krb5-workstation

  prepend_final: |
    RUN /usr/bin/microdnf install -y yum-utils \
        && microdnf upgrade -y \
        && microdnf install -y python39-pip python39-devel gcc \
        && python3 -m pip install --user --ignore-installed --no-cache-dir --upgrade pip setuptools wheel \
        && python3 -m pip install --user --ignore-installed --no-cache-dir --upgrade ansible-core ansible-runner 

  append_final: |
    ARG ANSIBLE_GALAXY_CLI_ROLE_OPTS=" --ignore-errors"
    RUN microdnf clean all \
      && rm -rf /var/cache/{dnf,yum} \
      && rm -rf /var/lib/dnf/history.* \
      && rm -rf /var/log/dnf.* /var/log/hawkey.log \
      && rm -rf /var/cache/dnf \
      && rm -rf /root/.cache \
      && rm -rf /etc/ansible/ansible.cfg
