---
- name: Clean up unused container images
  block:
    - name: Remove unused images
      ansible.builtin.command:
        cmd: podman image prune -f
      register: prune_result
      changed_when: prune_result.rc == 0

    - name: Debug prune results
      ansible.builtin.debug:
        msg: "Pruned unused images: {{ prune_result.stdout }}"

- name: Clean up old build artifacts
  block:
    - name: Remove old build artifacts
      ansible.builtin.file:
        path: "{{ work_dir }}/_build"
        state: absent
      register: cleanup_result

    - name: Debug cleanup results
      ansible.builtin.debug:
        msg: "Removed old build artifacts: {{ cleanup_result }}"

- name: Clean up temporary files
  block:
    - name: Remove temporary files
      ansible.builtin.file:
        path: /tmp/ee-containers
        state: absent
      ignore_errors: true

- name: Clean up temporary build directories
  ansible.builtin.file:
    path: "/tmp/ee-containers"
    state: absent
  ignore_errors: true
