---
- name: Remove temporary files and directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/tmp/ansible_safe"
    # Add other temp paths as needed
  ignore_errors: true

# Only cleanup selective subdirectories and files
- name: Clean up work directory selectively
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/tmp/ansible_safe"
    - "/tmp/ee-containers/hooks"
    - "/tmp/ee-containers/custom-assemble.sh"
  ignore_errors: true
