---
- name: Remove temporary files and directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/tmp/ee-banner.txt"
    - "/tmp/ee-builder"
    - "/tmp/ee-containers"
  ignore_errors: true
  become: true

- name: Prune all dangling container resources
  ansible.builtin.command:
    cmd: podman system prune -f
  register: system_prune_result
  changed_when: system_prune_result.rc == 0
  ignore_errors: true

- name: Display system prune results
  ansible.builtin.debug:
    msg: "{{ system_prune_result.stdout_lines }}"
  when: system_prune_result.stdout_lines is defined
