---
- name: Fix pattern {{ pattern_index }} in {{ environment }}  ansible.builtin.replace:
    path: "/tmp/ee-containers/environments/{{ environment }}/execution-environment.yml"
    regexp: "{{ item_regexes[pattern_index] }}"
    replace: "{{ item_replaces[pattern_index] }}"
  ignore_errors: true
  vars:
    item_regexes:
      - "additional_build_steps:[\\s\\n]+prepend:"
      - '(\s+)RUN\s+/output/scripts/pip_install'
      - "version:\\s+['\"]?2['\"]?"
      - "ansible.posix:[^\\n]+"
      - "(\n\\s+)(pip|dnf|yum)\\s+install"
    item_replaces:
      - "additional_build_steps:\n  prepend_base:"
      - '\1/output/scripts/pip_install'
      - "version: 3"
      - "ansible.posix: '>=1.5.1'"
      - "\\1microdnf install -y"
