---
- name: Find all task files
  ansible.builtin.find:
    paths: "{{ playbook_dir }}/roles/ee-builder/tasks"
    patterns: "*.yml"
  register: task_files

- name: Fix copy tasks with both src and content
  ansible.builtin.replace:
    path: "{{ item.path }}"
    regexp: "(ansible\\.builtin\\.copy:[\\s\\S]*?src: \"\\{\\{ .*? \\}\\}[\\s\\S]*?)content: \\|[\\s\\S]*?(\\n[^ -])"
    replace: "\\1\\2"
  with_items: "{{ task_files.files }}"