---
- name: Login to container registries
  block:
    - name: Login to container registry
      ansible.builtin.command:
        cmd: >
          podman login {{ item }} 
          -u {{ rh_username }}
          -p {{ rh_password }}
          --authfile {{ user_home }}/.docker/config.json
      loop: "{{ container_registries }}"
      register: registry_login
      when: 
        - rh_username is defined and rh_username != ""
        - rh_password is defined and rh_password != ""
      no_log: true
      failed_when: false

    - name: Check login results
      ansible.builtin.debug:
        msg: "Failed to login to {{ item.item }}. Will retry with alternative credentials."
      loop: "{{ registry_login.results }}"
      loop_control:
        label: "{{ item.item }}"
      when: item.rc is defined and item.rc != 0
      no_log: false
