---
# filepath: /home/sgallego/Downloads/GIT/ee-containers/roles/ee-builder/tasks/main.yml
# Main task file for the ee-builder role

- name: Build Execution Environment
  ansible.builtin.import_tasks: build_environment.yml
  tags:
    - build
