---
# EE Builder Role Main Tasks File

# === INITIALIZATION PHASE ===
- name: Handle credentials
  ansible.builtin.import_tasks: credentials.yml
  tags: ['init', 'creds']

- name: Set up build environment
  ansible.builtin.import_tasks: setup.yml
  tags: ['init', 'setup']

- name: Fix Red Hat registry authentication
  ansible.builtin.import_tasks: registry_auth.yml
  tags: ['init', 'auth']

- name: Fix execution environment files
  ansible.builtin.import_tasks: fix_ee_files.yml
  tags: ['init', 'fix']

# === VARIABLES AND CONFIGURATION ===
- name: Include role variables
  ansible.builtin.include_vars:
    file: "{{ role_path }}/vars/main.yml"

- name: Include configuration variables
  ansible.builtin.include_vars:
    file: "common-ee-vars.yml"

- name: Set role facts
  ansible.builtin.include_tasks: set_facts.yml
  tags: ['build']

# === ENVIRONMENT SELECTION ===
- name: Get environment selection from user
  ansible.builtin.include_tasks: environment_menu.yml
  tags: ['menu', 'build']

# === MONITORING SETUP ===
- name: Launch smart TMux monitoring system
  ansible.builtin.include_tasks: tmux_monitor.yml
  tags: ['monitor', 'build']
  when: environments_to_build is defined and environments_to_build | length > 0

# === BUILD PROCESS ===
- name: Build selected environments
  ansible.builtin.include_tasks: build_environment.yml
  tags: ['build']
  when: environments_to_build is defined and environments_to_build | length > 0

# === REPORTING AND NOTIFICATION ===
- name: Generate build reports
  ansible.builtin.include_tasks: reporting.yml
  tags: ['report', 'build']
  when: environments_to_build is defined and environments_to_build | length > 0

# === CLEANUP PHASE ===
- name: Clean up temporary files
  ansible.builtin.include_tasks: cleanup.yml
  tags: ['cleanup']
  when: cleanup_enabled | default(true)
