---
# EE Builder Role Main Tasks File

# === INITIALIZATION PHASE ===
- name: Handle credentials
  ansible.builtin.import_tasks: credentials.yml
  tags:
    - init
    - credentials

- name: Set up build environment
  ansible.builtin.import_tasks: setup.yml
  tags:
    - init
    - setup

- name: Fix Red Hat registry authentication
  ansible.builtin.import_tasks: login_registry.yml
  tags:
    - init
    - auth

- name: Fix execution environment files
  ansible.builtin.import_tasks: fix_ee_files.yml
  tags:
    - init
    - fix

# === VARIABLES AND CONFIGURATION ===
- name: Include role variables
  ansible.builtin.include_vars:
    file: "{{ role_path }}/vars/main.yml"
  tags:
    - config
    - vars

- name: Include common configuration variables
  ansible.builtin.include_vars:
    file: "common-ee-vars.yml"
  tags:
    - config
    - vars

- name: Set role facts
  ansible.builtin.import_tasks: set_facts.yml
  tags:
    - config
    - vars

# === ENVIRONMENT SELECTION ===
- name: Get environment selection from user
  ansible.builtin.import_tasks: environment_menu.yml
  when: environments_to_build is defined and environments_to_build | length > 0
  tags:
    - menu
    - build

# === MONITORING SETUP ===
- name: Launch TMux monitoring system
  ansible.builtin.import_tasks: tmux_monitor.yml
  when: monitoring_enabled | default(false)
  tags:
    - monitor
    - build

# === BUILD PROCESS ===
- name: Build selected environments
  ansible.builtin.import_tasks: build_environment.yml
  when: environments_to_build is defined and environments_to_build | length > 0
  tags:
    - build

# === REPORTING AND NOTIFICATION ===
- name: Generate build reports
  ansible.builtin.import_tasks: reporting.yml
  when: environments_to_build is defined and environments_to_build | length > 0
  tags:
    - report
    - build

# === CLEANUP PHASE ===
- name: Clean up temporary files
  ansible.builtin.import_tasks: cleanup.yml
  when: cleanup_enabled | default(true)
  tags:
    - cleanup
