---
# Tasks for ee-builder role

# Handle credentials
- name: Handle credentials
  ansible.builtin.import_tasks: credentials.yml
  tags: ['init', 'creds']

# Set up the build environment
- name: Set up build environment
  ansible.builtin.import_tasks: setup.yml
  tags: ['init', 'setup']

# Fix Red Hat registry authentication
- name: Fix Red Hat registry authentication
  ansible.builtin.import_tasks: registry_auth.yml
  tags: ['init', 'auth']

# Fix execution environment files
- name: Fix execution environment files
  ansible.builtin.import_tasks: fix_ee_files.yml
  tags: ['init', 'fix']

# Include variables
- name: Include configuration variables
  ansible.builtin.include_vars:
    file: "common-ee-vars.yml"

# Display environment menu and get selection
- name: Get environment selection from user
  ansible.builtin.include_tasks: environment_menu.yml
  tags: ['menu', 'build']

# Set role facts
- name: Set role facts
  ansible.builtin.include_tasks: set_facts.yml
  tags: ['build']

# Launch tmux monitoring session
- name: Launch tmux monitoring session
  ansible.builtin.include_tasks: tmux_session2.yml
  tags: ['menu', 'build']

# Build selected environments
- name: Build selected environments
  ansible.builtin.include_tasks: build_environment.yml
  tags: ['menu', 'build']

# Cleanup temporary files
- name: Clean up temporary files
  ansible.builtin.include_tasks: cleanup.yml
  tags: ['cleanup']
  when: cleanup_enabled | default(true)
