---
- name: Check execution-environment.yml existence
  ansible.builtin.stat:
    path: "/tmp/ee-containers/environments/{{ env_name }}/execution-environment.yml"
  register: ee_yml_file

- name: Read execution-environment.yml content
  ansible.builtin.slurp:
    src: "/tmp/ee-containers/environments/{{ env_name }}/execution-environment.yml"
  register: ee_yml_content
  when: ee_yml_file.stat.exists

# Then in your main playbook:
- name: Process each environment
  include_tasks: process_env.yml
  vars:
    env_name: "{{ item.item }}"
  loop: "{{ env_exists.results }}"
  when: item.stat.exists and item.stat.isdir