---
# Set essential facts for the ee-builder role

- name: Generate timestamp for image tag
  ansible.builtin.set_fact:
    timestamp: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"

- name: Set default values if not provided
  ansible.builtin.set_fact:
    environments_to_build: "{{ environments_to_build | default(['rhel9-ee-minimal-general']) }}"
    registry_username: "{{ registry_username | default('') }}"
    registry_password: "{{ registry_password | default('') }}"
    ee_version: "{{ ee_version | default('3') }}"