---
# TMux Session Management for Build Monitoring

# 1. Validate required variables
- name: Ensure required variables are defined
  ansible.builtin.assert:
    that:
      - environments_to_build is defined
      - environments_to_build | length > 0
    fail_msg: "The 'environments_to_build' variable is not defined or empty."
  tags:
    - tmux
    - monitor
    - validation

# 2. Ensure monitoring directory exists
- name: Ensure monitoring directory exists
  ansible.builtin.file:
    path: "{{ paths.base }}"
    state: directory
    mode: 0755
  tags:
    - tmux
    - monitor
    - setup

# 3. Create tmux monitor script
- name: Create tmux monitor script
  ansible.builtin.template:
    src: "templates/tmux_monitor.sh.j2"
    dest: "{{ paths.scripts }}/tmux_monitor.sh"
    mode: "0755"
  tags:
    - tmux
    - monitor
    - setup

# 4. Create tmux session for build monitoring
- name: Check if tmux session already exists
  ansible.builtin.shell: tmux has-session -t podman_monitor 2>/dev/null
  register: tmux_session_exists
  failed_when: false
  changed_when: false
  tags:
    - tmux
    - monitor

- name: Kill existing tmux session if it exists
  ansible.builtin.command: tmux kill-session -t podman_monitor
  when: tmux_session_exists.rc == 0
  ignore_errors: true
  tags:
    - tmux
    - monitor

- name: Create tmux session for build monitoring
  ansible.builtin.shell: |
    tmux new-session -d -s podman_monitor -n monitor
    tmux split-window -h -t podman_monitor
    tmux send-keys -t podman_monitor:0.0 "cd {{ paths.base }} && {{ paths.scripts }}/tmux_monitor.sh" C-m
    tmux send-keys -t podman_monitor:0.1 "cd {{ paths.base }} && watch -n 2 podman images" C-m
    tmux select-pane -t 0
  args:
    executable: /bin/bash
  tags:
    - tmux
    - monitor

# 5. Display instructions for accessing monitor
- name: Show instructions for accessing monitor
  ansible.builtin.debug:
    msg: |
      🔍 Podman monitoring session created for {{ environments_to_build | join(', ') }}
      
      To view the monitoring session:
      1. Run in any terminal: tmux attach -t podman_monitor
      2. Or simply run: /tmp/podman-monitor.sh
      
      Session Layout:
      - Left pane: Build status monitor
      - Right pane: Container images list (updates every 2 seconds)
      
      Tmux basic commands:
      - Detach from session: Ctrl+B, then D
      - Switch panes: Ctrl+B, then arrow keys
      - Scroll: Ctrl+B, then [ (use arrow keys to scroll, q to exit scroll mode)
  tags:
    - tmux
    - monitor
    - debug
