---
# TMux Monitoring System for Build Process

# 1. Check if tmux is installed
- name: Check if tmux is installed
  ansible.builtin.command: which tmux
  register: tmux_install
  failed_when: false
  changed_when: false
  tags:
    - tmux
    - monitor
    - setup

- name: Install tmux if missing
  ansible.builtin.package:
    name: tmux
    state: present
  when: tmux_install.rc != 0
  become: true
  tags:
    - tmux
    - monitor
    - setup

# 2. Create TMux monitor script
- name: Create TMux monitor script
  ansible.builtin.template:
    src: "templates/tmux_monitor.sh.j2"
    dest: "{{ paths.scripts }}/tmux_monitor.sh"
    mode: "0755"
  tags:
    - tmux
    - monitor
    - setup

# 3. Launch TMux monitoring system
- name: Launch TMux monitoring system
  ansible.builtin.shell: "{{ paths.scripts }}/tmux_monitor.sh"
  async: 10
  poll: 0
  when: environments_to_build is defined and environments_to_build | length > 0
  tags:
    - tmux
    - monitor

# 4. Display instructions for accessing TMux session
- name: Show instructions for accessing TMux session
  ansible.builtin.debug:
    msg: |
      🔍 TMux monitoring session created for {{ environments_to_build | join(', ') }}
      
      To view the monitoring session:
      1. Run in any terminal: tmux attach -t ansible-builder
      
      Session Layout:
      - Top pane: Title banner
      - Middle pane: Build progress with spinner
      - Bottom pane: Real-time image listing (refreshes every 0.5s)
      
      Tmux basic commands:
      - Detach from session: Ctrl+B, then D
      - Switch panes: Ctrl+B, then arrow keys
      - Scroll: Ctrl+B, then [ (use arrow keys to scroll, q to exit scroll mode)
  tags:
    - tmux
    - monitor
    - debug