---
collections:
  - community.general
  - community.vmware
  - community.postgresql
  - vmware.vmware_rest
  - cloud.vmware_ops
  - vmware.vmware
  - ansible.hub
  - infra.aap_utilities
  - infra.controller_configuration
  - infra.aap_configuration
  - containers.podman
  - oneidentity.safeguardcollection
  - community.hashi_vault
