---
version: 3
images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel8:latest
    options:
      pull_policy: missing
      tls_verify: false


dependencies:
    galaxy: ansible-collections.yml
    python: python-packages.txt

additional_build_files:
    # Can be used to resolve collections from private automation hub
    - src: ansible.cfg
      dest: configs

options:
    package_manager_path: /usr/bin/microdnf

additional_build_steps:
    prepend_base:
        - RUN $PYCMD -m pip install --upgrade pip setuptools
              