---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25//ee-minimal-rhel9:latest
    options:
      pull_policy: missing
      tls_verify: false

dependencies:
  galaxy:
    collections:
      - { name: ansible.posix, version: 3.6.2 }
      - { name: ansible.utils, version: 5.1.2 }
      - { name: ansible.windows, version: 2.5.0 }
      - { name: chocolatey.chocolatey, version: 3.5.3 }
      - { name: community.general, version: 9.5.0 }
      - { name: community.windows, version: 2.3.0 }
      - { name: microsoft.ad, version: 3.7.1 }
  python:
    - requests-credssp>=2.0.0,<3.0.0

options:
  package_manager_path: /usr/bin/microdnf
